### ISSUE TITLE
Application error: a client-side exception has occurred.

### ISSUE THREAD

**Issue by animemandir** [gokoro/Ohys-Schedule#26]
Dunnu what is wrong but here - Application error: a client-side exception has occurred (see the browser console for more information).

![image](https://user-images.githubusercontent.com/78192713/165708457-8d1f501b-6bd5-4e1c-a7a6-9d2204a500ef.png)

**Comment by gokoro** [comment]
@animemandir Please change the type of display from list to card in another tab. It's not a fundamental solution, but it'll help you until I fix the bugs.
